// Canonical specialty list for Indian practice.
//
// Deliberately a curated constant rather than an API call: there is no
// free, stable, authoritative specialty API, and an offline list is
// faster, works when the network doesn't, and — most importantly — keeps
// the values consistent. Doctor.specialty is free text in the schema, and
// the public "browse by specialty" chips are generated by grouping on
// that column, so "Skin", "Dermatology" and "Dermatologist" typed by three
// different doctors would fragment into three chips. Picking from one list
// keeps that browse surface coherent.
//
// "Other" is offered so a rare specialty is never blocked — the form
// reveals a free-text box for it rather than forcing a wrong choice.

export interface SpecialtyGroup {
  label: string;
  options: string[];
}

export const OTHER_SPECIALTY = "Other";

export const SPECIALTY_GROUPS: SpecialtyGroup[] = [
  {
    label: "Primary care",
    options: ["General Physician", "Family Medicine", "Internal Medicine", "Pediatrician", "Geriatrician"],
  },
  {
    label: "Medicine specialities",
    options: [
      "Cardiologist",
      "Dermatologist",
      "Diabetologist",
      "Endocrinologist",
      "Gastroenterologist",
      "Hepatologist",
      "Hematologist",
      "Infectious Disease Specialist",
      "Nephrologist",
      "Neurologist",
      "Oncologist",
      "Pulmonologist",
      "Rheumatologist",
    ],
  },
  {
    label: "Surgical specialities",
    options: [
      "General Surgeon",
      "Cardiothoracic Surgeon",
      "ENT Surgeon",
      "Neurosurgeon",
      "Orthopedic Surgeon",
      "Plastic & Cosmetic Surgeon",
      "Surgical Oncologist",
      "Urologist",
      "Vascular Surgeon",
      "Bariatric Surgeon",
      "Proctologist",
    ],
  },
  {
    label: "Women & child health",
    options: ["Gynecologist & Obstetrician", "Neonatologist", "Pediatric Surgeon", "Fertility Specialist"],
  },
  {
    label: "Mental health",
    options: ["Psychiatrist", "Clinical Psychologist", "Counsellor", "De-addiction Specialist"],
  },
  {
    label: "Eye, dental & skin",
    options: ["Ophthalmologist", "Optometrist", "Dentist", "Orthodontist", "Periodontist", "Trichologist", "Cosmetologist"],
  },
  {
    label: "Diagnostics & support",
    options: ["Radiologist", "Pathologist", "Anesthesiologist", "Emergency Medicine", "Critical Care Specialist"],
  },
  {
    label: "Allied health",
    options: [
      "Physiotherapist",
      "Dietitian / Nutritionist",
      "Audiologist",
      "Speech Therapist",
      "Occupational Therapist",
      "Podiatrist",
      "Sports Medicine Specialist",
    ],
  },
  {
    label: "AYUSH",
    options: ["Ayurveda", "Homeopathy", "Unani", "Siddha", "Naturopathy", "Yoga & Naturopathy"],
  },
  {
    label: "Other",
    options: ["Sexologist", "Andrologist", "Venereologist", "Pain Management Specialist", OTHER_SPECIALTY],
  },
];
